
- name: Disable jenkins at boot and stopped service
  systemd:
    name: jenkins.service
    state: stopped
    enabled: false
    daemon_reload: yes
  ignore_errors: True  
  tags: jenkins

- name: Remove jenkins
  dnf:
    name: jenkins
    state: absent
  tags: jenkins

- name: Remove jenkins repository
  file: 
    path: /etc/yum.repos.d/jenkins.repo 
    state: absent
  tags: jenkins


- name: Removing port 8080/tcp for jenkins
  firewalld:
    port: 8080/tcp
    permanent: true
    immediate: true
    state: disabled
  tags: jenkins
